# Generated by Django 4.0.6 on 2022-08-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caneva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb', models.UUIDField()),
                ('point_noir', models.CharField(max_length=400)),
                ('commune', models.CharField(max_length=400)),
                ('localisation', models.CharField(max_length=600)),
                ('valeur_pk', models.CharField(max_length=400)),
                ('gps', models.FloatField()),
                ('nb_accidents', models.IntegerField()),
                ('nb_blesses', models.IntegerField()),
                ('nb_tues', models.IntegerField()),
                ('causes', models.TextField()),
                ('mesures', models.TextField()),
                ('observations', models.TextField()),
            ],
        ),
        # migrations.DeleteModel(
        #     name='User',
        # ),
    ]
