# Generated by Django 4.0.6 on 2022-08-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0003_topic_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
