# Generated by Django 4.0.6 on 2022-08-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0006_user'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='User',
        # ),
    ]
