# Generated by Django 4.0.6 on 2022-08-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0007_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
