# Generated by Django 4.0.6 on 2022-08-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0008_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
