# Generated by Django 4.0.6 on 2022-08-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0009_delete_room_delete_topic'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='caneva',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='caneva',
        #     name='nb',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
