# Generated by Django 4.0.6 on 2022-08-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0010_remove_caneva_id_alter_caneva_nb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caneva',
            name='nb',
        ),
    ]
