# Generated by Django 4.0.6 on 2022-08-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0011_remove_caneva_nb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='caneva',
            new_name='BlackSpot',
        ),
    ]
