# Generated by Django 4.0.6 on 2022-08-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0012_rename_caneva_blackspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='caneva',
            fields=[
                ('id_caneva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('trimestre', models.IntegerField()),
                ('wilaya', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blackspot',
            name='caneva_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BSTracker.caneva'),
        ),
    ]
