# Generated by Django 4.0.6 on 2022-08-08 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0014_alter_caneva_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caneva',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 15, 22, 38, 770089, tzinfo=utc)),
        ),
    ]
