# Generated by Django 4.0.6 on 2022-08-08 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0015_alter_caneva_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackspot',
            name='caneva_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BSTracker.caneva'),
        ),
        migrations.AlterField(
            model_name='caneva',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 16, 17, 3, 14009, tzinfo=utc)),
        ),
    ]
