# Generated by Django 4.0.6 on 2022-08-09 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0016_alter_blackspot_caneva_id_alter_caneva_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caneva',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 18, 2, 19, 407527, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caneva',
            name='trimestre',
            field=models.TextField(),
        ),
    ]
