# Generated by Django 4.0.6 on 2022-08-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0017_alter_caneva_date_alter_caneva_trimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caneva',
            name='date',
        ),
        migrations.AddField(
            model_name='caneva',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
