# Generated by Django 4.0.6 on 2022-08-10 23:09

import BSTracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0018_remove_caneva_date_caneva_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackspot',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=BSTracker.models.filepath),
        ),
    ]
