# Generated by Django 4.0.6 on 2022-08-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0019_blackspot_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackspot',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blackspot',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
