# Generated by Django 4.0.6 on 2022-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0020_blackspot_lat_blackspot_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='wilaya',
            fields=[
                ('id_wilaya', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name_wilaya', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
