# Generated by Django 4.0.6 on 2022-08-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0021_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='caneva',
            name='total_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caneva',
            name='total_dead',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caneva',
            name='total_injured',
            field=models.IntegerField(default=0),
        ),
    ]
