# Generated by Django 4.0.6 on 2022-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0022_caneva_total_acc_caneva_total_dead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caneva',
            name='total_PN',
            field=models.IntegerField(default=0),
        ),
    ]
