# Generated by Django 4.0.6 on 2022-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSTracker', '0023_caneva_total_pn'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id_report', models.BigIntegerField(primary_key=b'I01\n', serialize=False)),
                ('report_title', models.TextField()),
            ],
        ),
    ]
